FROM nginx:latest

ARG API_BASE_URL
ENV API_BASE_URL "$API_BASE_URL"

COPY index.html /usr/share/nginx/html/index.html
COPY scripts.js /usr/share/nginx/html/scripts.js
ADD airline_icons /usr/share/nginx/html/airline_icons

# Copy the EntryPoint
COPY ./entryPoint.sh /
RUN chmod +x entryPoint.sh

ENTRYPOINT ["/entryPoint.sh"]
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]